# Generated by Django 4.1.7 on 2023-03-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_name', models.CharField(max_length=500, verbose_name='Операция')),
                ('currency', models.IntegerField(verbose_name='Валюта')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время сделки')),
            ],
        ),
    ]
